# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: 127.0.0.1
  database: shiyingbi
  username: root
  password: sruce3gvvnbs7
  port: 3306
  redis_url: "redis://@127.0.0.1/12"

# Production environment deploy by cap. And there settings are invalid.
production:
  <<: *default
  database: shiyingbi
  redis_url: "redis://@127.0.0.1:6379/12"
  username: erp
  password: nH8pcGtheetN
  port: 3306
  host: 8.218.141.146
  socket: /var/run/mysqld/mysqlx.sock